import type { DownloadFile } from "@/types/domain";

const IMG = "/assets/placeholder/downloads";

type Seed = Omit<DownloadFile, "id" | "createdAt" | "updatedAt">;

export const downloadSeed: Seed[] = [
  {
    slug: "aso-3d-source-55mm-frame",
    title: "55mm 프레임 시스템 3D 소스",
    category: "3d_source",
    version: "v3.2",
    fileType: "SKP",
    fileSize: "48.2 MB",
    fileUrl: "/assets/placeholder/files/aso-3d-55mm.skp",
    thumbnail: `${IMG}/3d-55mm.jpg`,
    description: "55mm 프레임 기본 유닛, 조인트, 코너 커넥터가 포함된 SketchUp 3D 소스입니다.",
    accessLevel: "member",
    status: "published",
  },
  {
    slug: "aso-3d-source-124mm-frame",
    title: "124mm 프레임 시스템 3D 소스",
    category: "3d_source",
    version: "v3.1",
    fileType: "3DS",
    fileSize: "62.7 MB",
    fileUrl: "/assets/placeholder/files/aso-3d-124mm.3ds",
    thumbnail: `${IMG}/3d-124mm.jpg`,
    description: "대형 구조물 설계를 위한 124mm 프레임 3D 소스 (3DS 포맷)입니다.",
    accessLevel: "member",
    status: "published",
  },
  {
    slug: "aso-system-design-manual",
    title: "ASO System 디자인 매뉴얼",
    category: "design_manual",
    version: "v5.0",
    fileType: "PDF",
    fileSize: "18.4 MB",
    fileUrl: "/assets/placeholder/files/aso-design-manual.pdf",
    thumbnail: `${IMG}/design-manual.jpg`,
    description: "시스템 철학, 모듈 규격, 디자인 가이드라인을 총정리한 공식 매뉴얼입니다.",
    accessLevel: "public",
    status: "published",
  },
  {
    slug: "aso-assembly-manual",
    title: "현장 조립 매뉴얼",
    category: "assembly_manual",
    version: "v2.4",
    fileType: "PDF",
    fileSize: "12.1 MB",
    fileUrl: "/assets/placeholder/files/aso-assembly-manual.pdf",
    thumbnail: `${IMG}/assembly-manual.jpg`,
    description: "프레임 연결, 그래픽 설치, 해체 순서를 단계별로 안내하는 현장용 매뉴얼입니다.",
    accessLevel: "staff",
    status: "published",
  },
  {
    slug: "aso-graphic-guideline",
    title: "그래픽 제작 가이드라인",
    category: "graphic_guideline",
    version: "v1.8",
    fileType: "PDF",
    fileSize: "9.6 MB",
    fileUrl: "/assets/placeholder/files/aso-graphic-guideline.pdf",
    thumbnail: `${IMG}/graphic-guideline.jpg`,
    description: "SEG, 포맥스, 월그래픽 등 소재별 도련·해상도 규격을 안내합니다.",
    accessLevel: "public",
    status: "published",
  },
  {
    slug: "aso-product-catalog-2025",
    title: "2025 종합 제품 카탈로그",
    category: "product_catalog",
    version: "2025",
    fileType: "PDF",
    fileSize: "24.9 MB",
    fileUrl: "/assets/placeholder/files/aso-catalog-2025.pdf",
    thumbnail: `${IMG}/catalog.jpg`,
    description: "시스템 부스 디자인, 비품, 프레임 제품군을 아우르는 종합 카탈로그입니다.",
    accessLevel: "public",
    status: "published",
  },
  {
    slug: "aso-frame-specification",
    title: "프레임 규격 및 하중 기준표",
    category: "specification",
    version: "v2.0",
    fileType: "PDF",
    fileSize: "3.2 MB",
    fileUrl: "/assets/placeholder/files/aso-frame-spec.pdf",
    thumbnail: `${IMG}/spec.jpg`,
    description: "55mm/124mm 프레임의 단면 규격, 허용 하중, 소재 사양을 정리한 기술 자료입니다.",
    accessLevel: "public",
    status: "published",
  },
  {
    slug: "aso-cad-drawing-pack",
    title: "표준 CAD 도면 세트",
    category: "cad_drawing",
    version: "v1.5",
    fileType: "DWG",
    fileSize: "5.8 MB",
    fileUrl: "/assets/placeholder/files/aso-cad-pack.dwg",
    thumbnail: `${IMG}/cad.jpg`,
    description: "부스 평면도 및 입면도 작성을 위한 표준 CAD 블록 세트입니다.",
    accessLevel: "member",
    status: "published",
  },
];
