import type { Inquiry } from "@/types/domain";

type Seed = Omit<Inquiry, "id" | "createdAt" | "updatedAt" | "internalNotes"> & {
  internalNotes: Omit<Inquiry["internalNotes"][number], "id" | "createdAt">[];
};

export const inquirySeed: Seed[] = [
  {
    inquiryNumber: "ASO-INQ-20260112-001",
    company: "그린텍에너지(주)",
    contactName: "박지현",
    email: "jhpark@greentech-energy.example.com",
    phone: "010-2233-4455",
    exhibition: "K-BATTERY SHOW 2026",
    country: "대한민국",
    city: "고양",
    eventDate: "2026-03-18",
    boothWidth: 12,
    boothDepth: 9,
    boothHeight: 4.5,
    budget: "5,000만원 ~ 7,000만원",
    boothDesignId: null,
    requirements: "이차전지 소재 기업입니다. 대형 아일랜드 부스로 타워와 미팅룸이 필요하며, 안전 인증 마크를 크게 노출하고 싶습니다.",
    attachments: [],
    status: "new",
    assigneeId: null,
    internalNotes: [],
  },
  {
    inquiryNumber: "ASO-INQ-20260108-002",
    company: "브이스페이스뷰티(주)",
    contactName: "이수민",
    email: "smlee@vspacebeauty.example.com",
    phone: "010-5566-7788",
    exhibition: "COSMOPROF KOREA 2026",
    country: "대한민국",
    city: "서울",
    eventDate: "2026-04-02",
    boothWidth: 6,
    boothDepth: 4,
    boothHeight: 3,
    budget: "1,500만원 ~ 2,000만원",
    boothDesignId: null,
    requirements: "제품 진열이 핵심입니다. 조명 연출과 쇼케이스 구성 예시를 받아보고 싶습니다.",
    attachments: [],
    status: "reviewing",
    assigneeId: null,
    internalNotes: [
      { authorId: "seed-staff", authorName: "정민호", note: "고객사에 유사 사례 3건 회신 예정. 코스메틱 포트폴리오 링크 전달함." },
    ],
  },
  {
    inquiryNumber: "ASO-INQ-20251228-003",
    company: "한국스타트업진흥원",
    contactName: "최동혁",
    email: "dhchoi@kstartup.example.com",
    phone: "02-3456-7890",
    exhibition: "CES 2027 Korea Pavilion",
    country: "미국",
    city: "라스베이거스",
    eventDate: "2027-01-06",
    boothWidth: 24,
    boothDepth: 12,
    boothHeight: 4.5,
    budget: "협의 필요 (정부 사업 예산)",
    boothDesignId: null,
    requirements: "작년과 동일한 국가관 컨셉으로 30개사 입주 규모입니다. 설치·철거 일정 단축 방안이 필요합니다.",
    attachments: [],
    status: "assigned",
    assigneeId: "seed-staff",
    internalNotes: [
      { authorId: "seed-admin", authorName: "김대표", note: "작년 담당자 그대로 배정. 예산안 초안 회신 요청." },
    ],
  },
  {
    inquiryNumber: "ASO-INQ-20251220-004",
    company: "어반크래프트퍼니처(주)",
    contactName: "한지원",
    email: "jwhan@urbancraft.example.com",
    phone: "010-9988-7766",
    exhibition: "국제가구산업대전 2026",
    country: "대한민국",
    city: "서울",
    eventDate: "2026-05-14",
    boothWidth: 9,
    boothDepth: 6,
    boothHeight: 3.3,
    budget: "3,000만원 내외",
    boothDesignId: null,
    requirements: "작년 부스 디자인(ASO-B-0006 유사)을 기반으로 진열대만 새 컬렉션에 맞게 교체하고 싶습니다.",
    attachments: [],
    status: "quoting",
    assigneeId: "seed-staff",
    internalNotes: [
      { authorId: "seed-staff", authorName: "정민호", note: "견적서 v1 작성 중. 진열대 3종 옵션 준비." },
    ],
  },
  {
    inquiryNumber: "ASO-INQ-20251115-005",
    company: "한솔푸드테크(주)",
    contactName: "장서연",
    email: "syjang@hansolfoodtech.example.com",
    phone: "010-1122-3344",
    exhibition: "서울푸드 2025",
    country: "대한민국",
    city: "고양",
    eventDate: "2025-05-13",
    boothWidth: 10,
    boothDepth: 8,
    boothHeight: 4,
    budget: "4,000만원",
    boothDesignId: null,
    requirements: "지난 전시와 동일 규모, 시식 카운터 2개 추가 요청.",
    attachments: [],
    status: "closed",
    assigneeId: "seed-staff",
    internalNotes: [
      { authorId: "seed-staff", authorName: "정민호", note: "프로젝트 완료. 포트폴리오 hansol-foodtech-seoulfood-2024 갱신 완료." },
    ],
  },
];
