import type { Portfolio } from "@/types/domain";

const IMG = "/assets/placeholder/portfolio";

export const portfolioSeed: Omit<Portfolio, "id" | "createdBy" | "createdAt" | "updatedAt">[] = [
  {
    slug: "kdigital-semicon-sedex-2025",
    title: "K-Digital 반도체 장비 전시부스",
    client: "케이디지털반도체(주)",
    exhibition: "SEDEX 2025 반도체대전",
    year: 2025,
    country: "대한민국",
    city: "서울 (COEX)",
    boothWidth: 12,
    boothDepth: 9,
    boothHeight: 4.2,
    projectType: "exhibition_booth",
    industry: "반도체·전자장비",
    systemType: "124mm",
    description:
      "124mm 프레임 시스템을 기반으로 대형 아일랜드 부스를 구성했습니다. 중앙 타워형 구조에 LED 스크린과 제품 쇼케이스를 결합하여 장비의 정밀함을 강조했고, 상담을 위한 밀폐형 미팅룸 2개를 후면에 배치했습니다. 동일 프레임 자재는 이후 자동차부품전에서 코너형 부스로 재구성되어 재사용되었습니다.",
    thumbnail: `${IMG}/kdigital-01.jpg`,
    gallery: [`${IMG}/kdigital-01.jpg`, `${IMG}/kdigital-02.jpg`, `${IMG}/kdigital-03.jpg`, `${IMG}/kdigital-04.jpg`],
    featured: true,
    status: "published",
    sortOrder: 1,
  },
  {
    slug: "seoul-motor-show-evmotors-2025",
    title: "EV모터스 서울모빌리티쇼 브랜드관",
    client: "이브이모터스(주)",
    exhibition: "2025 서울모빌리티쇼",
    year: 2025,
    country: "대한민국",
    city: "고양 (KINTEX)",
    boothWidth: 20,
    boothDepth: 16,
    boothHeight: 6,
    projectType: "brand_space",
    industry: "모빌리티·자동차",
    systemType: "mixed",
    description:
      "55mm와 124mm 프레임을 혼합해 6m 높이의 대형 브랜드관을 구현했습니다. 차량 회전 플랫폼을 중심으로 유리 캐노피와 브리지 구조를 적용해 개방감을 살렸으며, 상부 사인 시스템으로 원거리 시인성을 확보했습니다.",
    thumbnail: `${IMG}/evmotors-01.jpg`,
    gallery: [`${IMG}/evmotors-01.jpg`, `${IMG}/evmotors-02.jpg`, `${IMG}/evmotors-03.jpg`],
    featured: true,
    status: "published",
    sortOrder: 2,
  },
  {
    slug: "glowlab-cosmoprof-2024",
    title: "글로우랩 코스모프로프 쇼룸",
    client: "글로우랩코스메틱(주)",
    exhibition: "COSMOPROF KOREA 2024",
    year: 2024,
    country: "대한민국",
    city: "서울 (COEX)",
    boothWidth: 8,
    boothDepth: 6,
    boothHeight: 3.6,
    projectType: "showroom",
    industry: "뷰티·코스메틱",
    systemType: "55mm",
    description:
      "55mm 프레임 시스템으로 제품 전시형 쇼룸을 구성했습니다. 포맥스 그래픽과 SEG 그래픽을 병행 적용해 브랜드 톤을 유지하면서도 조명 연출에 따라 분위기를 바꿀 수 있도록 설계했습니다.",
    thumbnail: `${IMG}/glowlab-01.jpg`,
    gallery: [`${IMG}/glowlab-01.jpg`, `${IMG}/glowlab-02.jpg`],
    featured: true,
    status: "published",
    sortOrder: 3,
  },
  {
    slug: "hansol-foodtech-seoulfood-2024",
    title: "한솔푸드테크 서울푸드 체험관",
    client: "한솔푸드테크(주)",
    exhibition: "서울푸드 2024",
    year: 2024,
    country: "대한민국",
    city: "고양 (KINTEX)",
    boothWidth: 10,
    boothDepth: 8,
    boothHeight: 4,
    projectType: "exhibition_booth",
    industry: "식품·F&B",
    systemType: "124mm",
    description:
      "시식 체험을 위한 오픈형 카운터 6개소와 냉장 쇼케이스를 통합 배치한 4면 오픈 아일랜드 부스입니다. 위생 기준에 맞춘 마감재를 적용하고, 동선 혼잡을 줄이기 위해 진입로를 넓게 확보했습니다.",
    thumbnail: `${IMG}/hansol-01.jpg`,
    gallery: [`${IMG}/hansol-01.jpg`, `${IMG}/hansol-02.jpg`, `${IMG}/hansol-03.jpg`],
    featured: false,
    status: "published",
    sortOrder: 4,
  },
  {
    slug: "k-battery-nextcell-2024",
    title: "넥스트셀 K-BATTERY SHOW 기술관",
    client: "넥스트셀에너지(주)",
    exhibition: "K-BATTERY SHOW 2024",
    year: 2024,
    country: "대한민국",
    city: "고양 (KINTEX)",
    boothWidth: 15,
    boothDepth: 10,
    boothHeight: 5,
    projectType: "exhibition_booth",
    industry: "이차전지·에너지",
    systemType: "124mm",
    description:
      "대형 타워와 브리지 구조로 셀 제조 공정을 스토리텔링 방식으로 전달하는 페닌슐라형 부스입니다. LED 미디어월과 창고 공간을 후면에 통합해 운영 효율을 높였습니다.",
    thumbnail: `${IMG}/nextcell-01.jpg`,
    gallery: [`${IMG}/nextcell-01.jpg`, `${IMG}/nextcell-02.jpg`, `${IMG}/nextcell-03.jpg`, `${IMG}/nextcell-04.jpg`],
    featured: true,
    status: "published",
    sortOrder: 5,
  },
  {
    slug: "urbancraft-furniture-fair-2023",
    title: "어반크래프트 국제가구산업대전",
    client: "어반크래프트퍼니처(주)",
    exhibition: "국제가구산업대전 2023",
    year: 2023,
    country: "대한민국",
    city: "서울 (COEX)",
    boothWidth: 9,
    boothDepth: 6,
    boothHeight: 3.3,
    projectType: "exhibition_booth",
    industry: "가구·인테리어",
    systemType: "55mm",
    description:
      "가구 브랜드 특유의 질감을 살리기 위해 벽체 그래픽 대신 우드 톤 마감재를 프레임에 결합한 코너형 부스입니다. 진열대와 쇼케이스 구성으로 제품 라인업을 층위별로 노출했습니다.",
    thumbnail: `${IMG}/urbancraft-01.jpg`,
    gallery: [`${IMG}/urbancraft-01.jpg`, `${IMG}/urbancraft-02.jpg`],
    featured: false,
    status: "published",
    sortOrder: 6,
  },
  {
    slug: "koreastartup-ces-pavilion-2024",
    title: "코리아스타트업관 CES 국가관",
    client: "한국스타트업진흥원",
    exhibition: "CES 2024 Korea Pavilion",
    year: 2024,
    country: "미국",
    city: "라스베이거스",
    boothWidth: 24,
    boothDepth: 12,
    boothHeight: 4.5,
    projectType: "event_space",
    industry: "정부·공공 파빌리온",
    systemType: "mixed",
    description:
      "30개 스타트업이 입주하는 국가관을 동일한 55mm 모듈로 표준화해 설치·해체 시간을 40% 단축했습니다. 개별 부스는 독립성을 유지하면서도 상부 사인과 그래픽 톤을 통일해 파빌리온 전체의 통일감을 살렸습니다.",
    thumbnail: `${IMG}/koreastartup-01.jpg`,
    gallery: [`${IMG}/koreastartup-01.jpg`, `${IMG}/koreastartup-02.jpg`, `${IMG}/koreastartup-03.jpg`],
    featured: true,
    status: "published",
    sortOrder: 7,
  },
  {
    slug: "brightoffice-hq-showroom-2023",
    title: "브라이트오피스 사옥 브랜드 쇼룸",
    client: "브라이트오피스퍼니처(주)",
    exhibition: "상설 브랜드 쇼룸 (전시회 외)",
    year: 2023,
    country: "대한민국",
    city: "성남 (판교)",
    boothWidth: 14,
    boothDepth: 10,
    boothHeight: 3.8,
    projectType: "corporate_office",
    industry: "오피스 가구",
    systemType: "55mm",
    description:
      "전시회가 아닌 사옥 로비의 상설 브랜드 쇼룸을 시스템 자재로 시공한 사례입니다. 향후 리뉴얼 시 벽체와 진열대 모듈만 교체해 전체 철거 없이 재구성할 수 있도록 설계했습니다.",
    thumbnail: `${IMG}/brightoffice-01.jpg`,
    gallery: [`${IMG}/brightoffice-01.jpg`, `${IMG}/brightoffice-02.jpg`],
    featured: false,
    status: "published",
    sortOrder: 8,
  },
];
