import type { RentalItem } from "@/types/domain";

const IMG = "/assets/placeholder/rental";

type Seed = Omit<RentalItem, "id" | "createdAt" | "updatedAt">;

export const rentalSeed: Seed[] = [
  { productCode: "RC-CH-001", slug: "aso-lounge-chair-01", name: "ASO 라운지 체어 01", category: "chair", width: 60, depth: 65, height: 78, color: "차콜 그레이", material: "패브릭 · 알루미늄 프레임", description: "미팅 공간과 라운지에 두루 어울리는 경량 알루미늄 프레임 체어입니다.", images: [`${IMG}/chair-01.jpg`], stockStatus: "in_stock", priceVisible: false, rentalPrice: null, featured: true, status: "published", sortOrder: 1 },
  { productCode: "RC-CH-002", slug: "aso-bar-stool-02", name: "ASO 바 스툴 02", category: "chair", width: 40, depth: 40, height: 75, color: "무광 블랙", material: "스틸 · PU 시트", description: "카운터 높이에 최적화된 스툴로, 하이 카운터 부스에 적합합니다.", images: [`${IMG}/chair-02.jpg`], stockStatus: "in_stock", priceVisible: false, rentalPrice: null, featured: false, status: "published", sortOrder: 2 },
  { productCode: "RC-TB-001", slug: "aso-meeting-table-round", name: "ASO 미팅 테이블 (원형)", category: "table", width: 90, depth: 90, height: 74, color: "화이트", material: "MDF 상판 · 메탈 다리", description: "소규모 상담용 원형 테이블로 미팅룸 구성에 자주 사용됩니다.", images: [`${IMG}/table-01.jpg`], stockStatus: "in_stock", priceVisible: false, rentalPrice: null, featured: true, status: "published", sortOrder: 3 },
  { productCode: "RC-TB-002", slug: "aso-high-table-bar", name: "ASO 하이 테이블", category: "table", width: 80, depth: 80, height: 110, color: "알루미늄 실버", material: "알루미늄 · 강화유리", description: "스탠딩 상담 및 음료 서비스용 하이 테이블입니다.", images: [`${IMG}/table-02.jpg`], stockStatus: "low_stock", priceVisible: false, rentalPrice: null, featured: false, status: "published", sortOrder: 4 },
  { productCode: "RC-SF-001", slug: "aso-modular-sofa-2seat", name: "ASO 모듈러 소파 (2인)", category: "sofa", width: 140, depth: 75, height: 80, color: "베이지", material: "패브릭", description: "라운지 존이나 VIP 상담 공간에 적합한 2인용 소파입니다.", images: [`${IMG}/sofa-01.jpg`], stockStatus: "in_stock", priceVisible: false, rentalPrice: null, featured: true, status: "published", sortOrder: 5 },
  { productCode: "RC-SF-002", slug: "aso-modular-sofa-corner", name: "ASO 모듈러 코너 소파", category: "sofa", width: 220, depth: 220, height: 80, color: "딥 차콜", material: "패브릭", description: "대형 라운지 구성을 위한 ㄱ자형 코너 소파입니다.", images: [`${IMG}/sofa-02.jpg`], stockStatus: "on_order", priceVisible: false, rentalPrice: null, featured: false, status: "published", sortOrder: 6 },
  { productCode: "RC-CT-001", slug: "aso-info-counter-straight", name: "ASO 인포메이션 카운터 (직선형)", category: "counter", width: 150, depth: 60, height: 100, color: "화이트 · 실버", material: "알루미늄 프레임 · 포맥스", description: "안내 데스크용 직선형 카운터로 로고 그래픽 삽입이 가능합니다.", images: [`${IMG}/counter-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 180000, featured: true, status: "published", sortOrder: 7 },
  { productCode: "RC-CT-002", slug: "aso-info-counter-curved", name: "ASO 인포메이션 카운터 (곡선형)", category: "counter", width: 180, depth: 70, height: 100, color: "차콜", material: "알루미늄 프레임 · 포맥스", description: "동선을 부드럽게 유도하는 곡선형 카운터입니다.", images: [`${IMG}/counter-02.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 220000, featured: false, status: "published", sortOrder: 8 },
  { productCode: "RC-DP-001", slug: "aso-display-tower-slim", name: "ASO 슬림 디스플레이 타워", category: "display", width: 40, depth: 40, height: 120, color: "화이트", material: "알루미늄 · 강화유리", description: "소품 및 시제품 전시에 적합한 슬림형 진열대입니다.", images: [`${IMG}/display-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 90000, featured: false, status: "published", sortOrder: 9 },
  { productCode: "RC-DP-002", slug: "aso-display-plinth-set", name: "ASO 진열대 세트 (3단)", category: "display", width: 120, depth: 40, height: 90, color: "화이트", material: "MDF", description: "높이가 다른 3개 좌대로 구성된 제품 진열 세트입니다.", images: [`${IMG}/display-02.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 130000, featured: false, status: "published", sortOrder: 10 },
  { productCode: "RC-SC-001", slug: "aso-glass-showcase-tall", name: "ASO 유리 쇼케이스 (하이형)", category: "showcase", width: 60, depth: 60, height: 180, color: "투명 · 실버 프레임", material: "강화유리 · 알루미늄", description: "고가 제품 보호 전시에 적합한 잠금형 유리 쇼케이스입니다.", images: [`${IMG}/showcase-01.jpg`], stockStatus: "low_stock", priceVisible: true, rentalPrice: 250000, featured: true, status: "published", sortOrder: 11 },
  { productCode: "RC-SC-002", slug: "aso-glass-showcase-low", name: "ASO 유리 쇼케이스 (로우형)", category: "showcase", width: 100, depth: 50, height: 90, color: "투명 · 블랙 프레임", material: "강화유리 · 알루미늄", description: "다수 제품을 한눈에 비교 전시하기 좋은 로우형 쇼케이스입니다.", images: [`${IMG}/showcase-02.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 200000, featured: false, status: "published", sortOrder: 12 },
  { productCode: "RC-RF-001", slug: "aso-showcase-refrigerator", name: "ASO 쇼케이스 냉장고", category: "refrigerator", width: 60, depth: 60, height: 190, color: "블랙", material: "스틸 · 강화유리 도어", description: "식음료 시식 부스에 사용되는 유리도어 쇼케이스 냉장고입니다.", images: [`${IMG}/fridge-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 150000, featured: false, status: "published", sortOrder: 13 },
  { productCode: "RC-TV-001", slug: "aso-monitor-55in-stand", name: "ASO 55형 모니터 (스탠드형)", category: "tv_monitor", width: 30, depth: 30, height: 165, color: "블랙", material: "메탈 스탠드", description: "제품 소개 영상 송출용 55형 스탠드 모니터입니다.", images: [`${IMG}/tv-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 180000, featured: true, status: "published", sortOrder: 14 },
  { productCode: "RC-TV-002", slug: "aso-monitor-75in-wall", name: "ASO 75형 모니터 (벽부형)", category: "tv_monitor", width: 172, depth: 10, height: 100, color: "블랙", material: "벽부 브래킷", description: "메인 그래픽월에 매립 설치하는 대형 벽부형 모니터입니다.", images: [`${IMG}/tv-02.jpg`], stockStatus: "low_stock", priceVisible: true, rentalPrice: 320000, featured: false, status: "published", sortOrder: 15 },
  { productCode: "RC-LT-001", slug: "aso-spot-light-track", name: "ASO 스팟 조명 (트랙형)", category: "lighting", width: 10, depth: 10, height: 20, color: "블랙", material: "알루미늄", description: "제품과 그래픽월을 강조하는 트랙 스팟 조명입니다.", images: [`${IMG}/light-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 25000, featured: false, status: "published", sortOrder: 16 },
  { productCode: "RC-LT-002", slug: "aso-pendant-light-round", name: "ASO 펜던트 조명 (원형)", category: "lighting", width: 40, depth: 40, height: 40, color: "화이트", material: "알루미늄 · 아크릴", description: "라운지 공간 분위기 연출용 원형 펜던트 조명입니다.", images: [`${IMG}/light-02.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 40000, featured: false, status: "published", sortOrder: 17 },
  { productCode: "RC-KT-001", slug: "aso-pantry-counter-set", name: "ASO 팬트리 카운터 세트", category: "kitchen", width: 180, depth: 60, height: 90, color: "화이트", material: "스틸 · 인조대리석", description: "시음·시식 부스를 위한 싱크대 일체형 팬트리 카운터입니다.", images: [`${IMG}/kitchen-01.jpg`], stockStatus: "on_order", priceVisible: true, rentalPrice: 280000, featured: false, status: "published", sortOrder: 18 },
  { productCode: "RC-AC-001", slug: "aso-brochure-stand", name: "ASO 브로슈어 스탠드", category: "accessories", width: 30, depth: 30, height: 100, color: "실버", material: "알루미늄", description: "카탈로그·브로슈어 비치용 스탠드입니다.", images: [`${IMG}/accessory-01.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 15000, featured: false, status: "published", sortOrder: 19 },
  { productCode: "RC-AC-002", slug: "aso-coat-hanger-rack", name: "ASO 코트 행거", category: "accessories", width: 60, depth: 40, height: 160, color: "블랙", material: "스틸", description: "스태프룸 및 VIP존에 배치하는 의류 행거입니다.", images: [`${IMG}/accessory-02.jpg`], stockStatus: "in_stock", priceVisible: true, rentalPrice: 12000, featured: false, status: "published", sortOrder: 20 },
];
